<a href="https://colab.research.google.com/github/LaFFF2300/Citie/blob/main/Activity_One_Python_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# WELOME TO PYTHON FUNDAMENTALS
In this module, we are going to establish or review our skills in Python programming. In this notebook we are going to cover:
* Variables and Data Types 
* Operations
* Input and Output Operations
* Logic Control
* Iterables
* Functions

## Variebles and Data types

In [ ]:
x = 1
i,j = 2, 13

In [ ]:
type(x)

int

In [ ]:
y = 1.0
type(y)

In [ ]:
x = float(x)
type(x)

In [ ]:
s,t,u = "0", '1', 'one'
type(s)

In [ ]:
s_int = int(s)
s_int

0

OPERATION

# Arithmetic

In [ ]:
a,b,c,d = 5.0,-3.5, 8, -32

In [ ]:
#Addition
S = a+b
S

1.5

In [ ]:
###Subtraction
D = b-d
D

28.5

In [ ]:
###Multiplication
P = a*d
P

-160.0

In [ ]:
###Division 
Q = c/a
Q

1.6

In [ ]:
###Floor Division
Fq = a//b
Fq

-2.0

In [ ]:
###Exponentiation
E = a**b
E

0.0035777087639996636

In [ ]:
###Modulo
mod = d%a
mod

3.0

# Assignment Operation

In [ ]:
G,H,J,K = 0, 100, 2, 2

In [ ]:
G += a
G

5.0

In [ ]:
H -= d 
H

132

In [ ]:
J *= 2
J 

4

In [ ]:
K **= 3 
K 

8

## Comparators

In [ ]:
res_1, res_2, res_3 = 1, 2.0, "1" 
true_val = 1.0 

In [ ]:
## Equality
res_1 == true_val

True

In [ ]:
## Non-Equality
res_2 != true_val 

True

In [ ]:
## Inequality
t1 = res_1 > res_2 
t2 = res_1 < res_2/2 
t3 = res_1 >= res_2/2
t4 = res_1 <= res_2 

## Logical

In [ ]:
res_1 == true_val 

True

In [ ]:
res_1 is true_val 

False

In [ ]:
res_1 is not true_val 

True

In [ ]:
p, q = True, False 
conj = p and q 
conj

False

In [ ]:
p, q = True, False
disj = p or q 
disj

True

In [ ]:
p, q = True, False 
nand = not (p and q) 
nand

True

In [ ]:
p, q = True, False 
xor = (not p and q) or (p and not q) 
xor 

True

## ----

In [ ]:
print("Hello Universe") 

Hello Universe


In [ ]:
cnt = 1 

In [ ]:
string = "Hello Universe" 
print(string, ", Current run count is:", cnt) 
cnt+= 1

Hello Universe , Current run count is: 1


In [ ]:
print(f"{string}, Current count is: {cnt}")

Hello Universe, Current count is: 2


In [ ]:
sem_grade = 98
name = "Alex cutie" 
print("Hello {}, your semestral grade is: {}". format (name, sem_grade))

Hello Alex cutie, your semestral grade is: 98


In [ ]:
w_pg, w_mg, w_fg = 0.3, 0.3, 0.4 
print("The weights of your semestral grades are:\
\n\t{:.2%} for Prelims\
\n\t{:.2%} for Midterms, and\
\n\t{:.2%} for Finals.". format(w_pg, w_mg, w_fg))

The weights of your semestral grades are:
	30.00% for Prelims
	30.00% for Midterms, and
	40.00% for Finals.


In [ ]:
x = input ("enter a number: ")
x

enter a number: 98


'98'

In [ ]:
name = input("Kimi no nawa: ")
pg = input("Enter prelims grade: ") 
mg = input("Enter midterms grade: ")
fg = input("Enter finals grade: ")
sem_grade = 98
print("Hello {}, your semestral grade is: {}".format(name, sem_grade))

Kimi no nawa: 98
Enter prelims grade: 97
Enter midterms grade: 98
Enter finals grade: 99
Hello 98, your semestral grade is: 98


##**Looping** **Statement**

In [ ]:
## while loops
i, j =0,10
while(i<=j):
  print(f"{i}\t|\t{j}")
  i+=1

0	|	10
1	|	10
2	|	10
3	|	10
4	|	10
5	|	10
6	|	10
7	|	10
8	|	10
9	|	10
10	|	10


In [ ]:
# for(int i=o; i<10; i++){
# printf(1)
# }

i=0
for i in range(11):
  print(i)

0
1
2
3
4
5
6
7
8
9
10


In [ ]:
playlist = ["Stargazing", "10 minute version", "Happier- ed"]
print('Now Playing:\n')
for song in playlist:
  print(song)

Now Playing:

Stargazing
10 minute version
Happier- ed


##Flow Control

###Condition Statement

In [ ]:
numeral1, numeral2 = 12, 14
if(numeral1 == numeral2):
  print("NYENYENYE")
elif(numeral1>numeral2):
  print("Blehhh")
else:
  print("Ampon")

Ampon


##Functions

In [ ]:
# void DeleteUser(int userid){
#    delete(userid);
# }

def delete_user (userid):
  print("Successfully Deleted user: {}".format(userid))

def delete_all_user ():
  print("Successfully deleted all user")

In [ ]:
userid = 202013010
delete_user(202013010)
delete_all_user()

Successfully Deleted user: 202013010
Successfully deleted all user


In [ ]:
def add(addend1, addend2):
  print("I Am Great at adding Addends mwehehehe botbot")
  return addend1 + addend2
  
def power_of_base2(exponent):
  return 28**exponent

addend1 = 5
addend2 = 15

exponent = 3

add(addend1, addend2)
power_of_base2(exponent)

I Am Great at adding Addends mwehehehe botbot


21952

In [ ]:
add(addend1, addend2)

I Am Great at adding Addends mwehehehe botbot


20

##Lamba Functions

##Discussion

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as plt
%matplotlib inline

$$
A = \left\{
    \begin{array}\
        x + y\\
        4x - 10y
    \end{array}
\right.\\
B = \left\{
    \begin{array}\
      x+y+z \\
      3x -2y -z \\
      -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      w-2x+3y-4z \\
      3w- x -2y +z \\
      2w -x + 3y - 2z
    \end{array}
\right. 
$$

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}
$$

In [6]:
$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{(i-1,j-1)}
\end{bmatrix}
$$

SyntaxError: ignored

In [7]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [8]:
A = np.array([
    [1, 2],
    [3, 1]
])

In [9]:
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [11]:
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)

Matrix:
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [13]:
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [14]:
H = np.array([1,2,3,4])
describe_mat(H)

Matrix:
[1 2 3 4]

Shape:	(4,)
Rank:	1



## Declaring a Row Matrix

In [15]:
rowmatrix1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)

Matrix:
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [16]:
col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



In [18]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [19]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



In [20]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

In [21]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [22]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [24]:
d = np.diag([2,3,5,7])

In [25]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [26]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [28]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)

array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

In [ ]:
np.tril(F)

In [ ]:
np.array([
          [2,0,0]
          []
])

##Identity Matrix