<a href="https://colab.research.google.com/github/LaFFF2300/Citie/blob/main/Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Linear Algebra for ChE
##Assignment 3 : Matrices

### Objectives

At the end of this activity, you will be able to do the following:
1. Understand matrices and how they relate to linear equations.
2. Perform basic matrix operations.
3. Matrix equations and operations can be programmed and translated using Python.

##Discussion

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as plt
%matplotlib inline

##Matrices

One of the fundamentals of modern computing is the use and notation of matrices. Matrices can also be used to represent complex equations or multiple interconnected equations, ranging from 2-dimensional to hundreds of thousands of them.

$$
A = \left\{
    \begin{array}\
        x + y\\
        4x - 10y
    \end{array}
\right.\\
B = \left\{
    \begin{array}\
      x+y+z \\
      3x -2y -z \\
      -x + 4y +2z
    \end{array}
\right. \\
C = \left\{
    \begin{array}\
      w-2x+3y-4z \\
      3w- x -2y +z \\
      2w -x + 3y - 2z
    \end{array}
\right. 
$$

*X* is a two-parameter system of two equations, as we can see. Y, on the other hand, is a three-equation, three-parameter system. They can be represented as matrices in the following ways:

$$
A=\begin{bmatrix} 1 & 1 \\ 4 & {-10}\end{bmatrix} \\
B=\begin{bmatrix} 1 & 1 & 1 \\ 3 & -2 & -1 \\ -1 & 4 & 2\end{bmatrix}\\
C=\begin{bmatrix} 1 & -2 & 3 & -4 \\ 3 & -1 & -2 & 1 \\ 2 & -1 & 3 & -2\end{bmatrix}
$$

Assuming you've already learned about matrix representation, types, and operations. From now on, we'll do them in Python.

#Declaring Matrices
We'll use a matrix to represent a system of linear equations, as we did in the previous laboratory activity. The entities or numbers that comprise matrices are referred to as matrix elements. The list/array structure of matrices is formed by arranging and ordering these elements in rows and columns. These elements are indexed in the same way that arrays are, based on their position in relation to their rows and columns. The following equation can be used to represent this. X, on the other hand, is a matrices composed of xi,j elements. The number of rows in the matrix is denoted by i, while the number of columns is denoted by j.
Keep in mind that the size of a matrix is i x j.

$$A=\begin{bmatrix}
a_{(0,0)}&a_{(0,1)}&\dots&a_{(0,j-1)}
\\
a_{(1,0)}&a_{(1,1)}&\dots&a_{(1,j-1)}
\\
\vdots&\vdots&\ddots&\vdots&\\
a_{(i-1,0)}&a_{(i-1,1)}&\dots&a_{
(i-1,j-1)}
\end{bmatrix}
$$

In [ ]:
def describe_mat(matrix):
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\n')

In [ ]:
A = np.array([
    [1, 2],
    [3, 1]
])
describe_mat(A)

Matrix:
[[1 2]
 [3 1]]

Shape:	(2, 2)
Rank:	2



In [ ]:
G = np.array([
    [1,1,3],
    [2,2,4]
])
describe_mat(G)

Matrix:
[[1 1 3]
 [2 2 4]]

Shape:	(2, 3)
Rank:	2



In [ ]:
B = np.array([
    [8, 2],
    [5, 4],
    [1, 1]
])
describe_mat(B)

Matrix:
[[8 2]
 [5 4]
 [1 1]]

Shape:	(3, 2)
Rank:	2



In [ ]:
H = np.array([1,2,3,4])
describe_mat(H)

Matrix:
[1 2 3 4]

Shape:	(4,)
Rank:	1



#Categorizing Matrices
Matrixes can be classified in several ways. One could be based on their element values, while the other on their shape. We'll do our best to go through them.

##According to shape


###Row and column matrices
Row and column matrices are frequently used in vector and matrix computations. They can also be used to represent a larger vector space's row and column spaces. A single column or row represents a row or column matrix. As a result, row matrices are 1 X j and column matrices are i x 1.

## Declaring a Row Matrix

In [ ]:
rowmatrix1D = np.array([
    1, 3, 2, -4
]) ## this is a 1-D Matrix with a shape of (3,), it's not really considered as a row matrix.
row_mat_2D = np.array([
    [1,2,3, -4]
]) ## this is a 2-D Matrix with a shape of (1,3)
describe_mat(rowmatrix1D)
describe_mat(row_mat_2D)

Matrix:
[ 1  3  2 -4]

Shape:	(4,)
Rank:	1

Matrix:
[[ 1  2  3 -4]]

Shape:	(1, 4)
Rank:	2



In [ ]:
col_mat = np.array([
    [1],
    [2],
    [5]
]) ## this is a 2-D Matrix with a shape of (3,1)
describe_mat(col_mat)

Matrix:
[[1]
 [2]
 [5]]

Shape:	(3, 1)
Rank:	2



##Square matrices
Square matrices have the same row and column dimensions. A matrix is said to be square if i=j. We can modify our matrix descriptor function to find square matrices.

In [ ]:
def describe_mat(matrix):
    is_square = True if matrix.shape[0] == matrix.shape[1] else False 
    print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')

In [ ]:
square_mat = np.array([
    [1,2,5],
    [3,3,8],
    [6,1,2]
])

non_square_mat = np.array([
    [1,2,5],
    [3,3,8]
])
describe_mat(square_mat)
describe_mat(non_square_mat)

Matrix:
[[1 2 5]
 [3 3 8]
 [6 1 2]]

Shape:	(3, 3)
Rank:	2
Is Square: True

Matrix:
[[1 2 5]
 [3 3 8]]

Shape:	(2, 3)
Rank:	2
Is Square: False



##According to element values

###Null Matrix
A Null Matrix is one that contains no elements. It's always a vector or a matrices subspace.

In [ ]:
def describe_mat(matrix):
    if matrix.size > 0:
        is_square = True if matrix.shape[0] == matrix.shape[1] else False 
        print(f'Matrix:\n{matrix}\n\nShape:\t{matrix.shape}\nRank:\t{matrix.ndim}\nIs Square: {is_square}\n')
    else:
        print('Matrix is Null')

In [ ]:
null_mat = np.array([])
describe_mat(null_mat)

##Zero Matrix
A zero matrix can be any rectangular matrix, but all of its elements must be 0 in order to be considered.

In [ ]:
zero_mat_row = np.zeros((1,2))
zero_mat_sqr = np.zeros((2,2))
zero_mat_rct = np.zeros((3,2))

print(f'Zero Row Matrix: \n{zero_mat_row}')
print(f'Zero Square Matrix: \n{zero_mat_sqr}')
print(f'Zero Rectangular Matrix: \n{zero_mat_rct}')

Zero Row Matrix: 
[[0. 0.]]
Zero Square Matrix: 
[[0. 0.]
 [0. 0.]]
Zero Rectangular Matrix: 
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##One Matrix
A ones matrix, like a zero matrix, can be any rectangular matrix whose elements are all 1s rather than 0s.

In [ ]:
ones_mat_row = np.ones((1,2))
ones_mat_sqr = np.ones((2,2))
ones_mat_rct = np.ones((3,2))

print(f'Ones Row Matrix: \n{ones_mat_row}')
print(f'Ones Square Matrix: \n{ones_mat_sqr}')
print(f'Ones Rectangular Matrix: \n{ones_mat_rct}')

Ones Row Matrix: 
[[1. 1.]]
Ones Square Matrix: 
[[1. 1.]
 [1. 1.]]
Ones Rectangular Matrix: 
[[1. 1.]
 [1. 1.]
 [1. 1.]]


##Diagonal Matrix
A diagonal matrix is a square matrix that only has values along one of its diagonals.

In [ ]:
np.array([
    [2,0,0],
    [0,3,0],
    [0,0,5]
])

array([[2, 0, 0],
       [0, 3, 0],
       [0, 0, 5]])

In [ ]:
d = np.diag([2,3,5,7])
#d.shape[0] == d.shape[1]
d

##Identity Matrix
An identity matrix is a diagonal matrix with all diagonal values equal to one.

In [ ]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

##Upper Triangular Matrix
An upper triangular matrix is one that has no values below the diagonal.

In [ ]:
np.array([
    [1,2,3,4],
    [0,3,1,-1],
    [0,0,5,2],
    [0,0,0,2]
])

array([[ 1,  2,  3,  4],
       [ 0,  3,  1, -1],
       [ 0,  0,  5,  2],
       [ 0,  0,  0,  2]])

In [ ]:
F = np.array([
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
              [2, -3, 4, -5, 6],
])
np.triu(F)

array([[ 2, -3,  4, -5,  6],
       [ 0, -3,  4, -5,  6],
       [ 0,  0,  4, -5,  6],
       [ 0,  0,  0, -5,  6],
       [ 0,  0,  0,  0,  6]])

##Lower Triangular Matrix
There are no values above the diagonal in a lower triangular matrix.

In [ ]:
np.array([
    [2,0,0],
    [10,6,0],
    [14,16,10]
])

array([[ 2,  0,  0],
       [10,  6,  0],
       [14, 16, 10]])

#Matrix Algebra

##Addition

In [ ]:
X = np.array([
    [2,4],
    [4,6],
    [8,2]
])
Y = np.array([
    [4,4],
    [0,0],
    [2,2]
])
X+Y

In [ ]:
4+X ##Broadcasting
# 4*np.ones(A.shape)+A

##Subtraction

In [ ]:
X-Y

In [ ]:
6-Y == 6*np.ones(Y.shape)-Y

##Element-wise Multiplication

In [ ]:
X*Y
np.multiply(X,Y)

In [ ]:
4*X

In [ ]:
X @ Y

In [ ]:
alpha=20**-20
X/(alpha+Y)

In [ ]:
np.add(X,Y)

#Activity

##Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:


1.   Displays the shape, size, and rank of the matrix.
2.   Displays whether the matrix is square or non-square.
3.   Displays whether the matrix is an empty matrix.
4.   Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [1]:
import numpy as np

In [2]:
# mat_desc function

def mat_desc(matrix):
  square = False
  matrix = np.array(matrix)
  print(matrix)
  print('Shape', matrix.shape)
  print('Size', matrix.size)
  print('Rank', np.linalg.matrix_rank(matrix))
  if(matrix.shape[0] == matrix.shape[1]):
    square = True
    print('Square Matrix')
  else: 
    print('Non-Square Matrix')
  if(matrix.shape[0] == 0 and matrix.shape[1] == 0):
    print('Empty Matrix')
  else:
    print('Matrix in not empty')
  iden = np.identity(matrix.shape[0])
  if(square and (iden == matrix).all()):
    print('Identity Matrix')
  else:
    print('Not identity matrix')
  one = np.ones((matrix.shape[0], matrix.shape[1]))
  if(one == matrix).all ():
    print('Ones matrix')
  else:
    print('Not a Ones Matrix')
  zero = np.zeros((matrix.shape[0], matrix.shape[1]))
  if((zero == matrix).all()):
    print('Zero Matrix')
  else:
    print('Non-Zero Matrix')

In [3]:
print ('Matrix 1:')
mat_desc([[12,14], [18,21], [23,25], [22,33], [5,5]])

print ('Matrix 2:')
mat_desc([[31,3], [19,25], [33,22], [12,12]])

print ('Matrix 3:')
mat_desc([[7,21], [3,5], [10,20], [5,7]])

print ('Matrix 4:')
mat_desc([[8,10], [12,20], [30,40], [12,18]])

print ('Matrix 5:')
mat_desc([[12,2,3], [14,2,28], [5,1,30]])

Matrix 1:
[[12 14]
 [18 21]
 [23 25]
 [22 33]
 [ 5  5]]
Shape (5, 2)
Size 10
Rank 2
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix 2:
[[31  3]
 [19 25]
 [33 22]
 [12 12]]
Shape (4, 2)
Size 8
Rank 2
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix 3:
[[ 7 21]
 [ 3  5]
 [10 20]
 [ 5  7]]
Shape (4, 2)
Size 8
Rank 2
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix 4:
[[ 8 10]
 [12 20]
 [30 40]
 [12 18]]
Shape (4, 2)
Size 8
Rank 2
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix 5:
[[12  2  3]
 [14  2 28]
 [ 5  1 30]]
Shape (3, 3)
Size 9
Rank 3
Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix


###Task 2


Create a function named mat_operations() that takes in two matrices a input parameters it should:



1.   Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2.   Returns the sum of the matrices.
3.   Returns the differen of the matrices.
4.   Returns the element-wise multiplication of the matrices.
5.   Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [4]:
def mat_operations(matrix1, matrix2):
    matrix1 = np.array(matrix1)
    matrix2 = np.array(matrix2)
    print('Matrix 1:', matrix1)
    print('Matrix 2:', matrix2)
    if(matrix1.shape != matrix2.shape):
        print('The matrices are not equal and invalid size operation.')
        return
    print('Sum of the  matrices:')
    matrixsum = matrix1 + matrix2
    print(matrixsum)
    print('Difference of the  matrices:')
    matrixdifference = matrix1 - matrix2
    print(matrixdifference)
    print('Element-wise multiplication of the  matrices:')
    matrixproduct = np.multiply(matrix1, matrix2)
    print(matrixproduct)
    print('Element-wise division of the  matrices:')
    matrixdividend = np.divide(matrix1, matrix2)
    print(matrixdividend)

In [5]:
print('sample1:')
mat_operations([[2,3,2], [5,4,7], [4,3,8]],[[3,4,5], [9,7,1],[1,2,6]])

print('sample 2:')
mat_operations([[2, 6, 3,4], [3,3,1,5], [5,1,5,7]], [[3,7,5,7],[1,2,1,9],[1,1,1,6]])

print('sample 3:')
mat_operations([[2, 5, 1], [3,6,3], [6,1,5]], [[5,4,2],[3,4,6],[3,2,3]])

print('sample 4:')
mat_operations([[6,2,1,8,2], [3,6,3,7,8], [6,1,5,9,2]], [[5,4,2,7,7],[3,4,6,8,9],[3,2,3,6,2]])

print('sample 5:')
mat_operations([[6,2,1,8,2,5], [3,6,3,7,8,8], [6,1,5,9,2,2]], [[5,4,2,7,7,8],[3,4,6,8,9,2],[3,2,3,6,2,1]])

sample1:
Matrix 1: [[2 3 2]
 [5 4 7]
 [4 3 8]]
Matrix 2: [[3 4 5]
 [9 7 1]
 [1 2 6]]
Sum of the  matrices:
[[ 5  7  7]
 [14 11  8]
 [ 5  5 14]]
Difference of the  matrices:
[[-1 -1 -3]
 [-4 -3  6]
 [ 3  1  2]]
Element-wise multiplication of the  matrices:
[[ 6 12 10]
 [45 28  7]
 [ 4  6 48]]
Element-wise division of the  matrices:
[[0.66666667 0.75       0.4       ]
 [0.55555556 0.57142857 7.        ]
 [4.         1.5        1.33333333]]
sample 2:
Matrix 1: [[2 6 3 4]
 [3 3 1 5]
 [5 1 5 7]]
Matrix 2: [[3 7 5 7]
 [1 2 1 9]
 [1 1 1 6]]
Sum of the  matrices:
[[ 5 13  8 11]
 [ 4  5  2 14]
 [ 6  2  6 13]]
Difference of the  matrices:
[[-1 -1 -2 -3]
 [ 2  1  0 -4]
 [ 4  0  4  1]]
Element-wise multiplication of the  matrices:
[[ 6 42 15 28]
 [ 3  6  1 45]
 [ 5  1  5 42]]
Element-wise division of the  matrices:
[[0.66666667 0.85714286 0.6        0.57142857]
 [3.         1.5        1.         0.55555556]
 [5.         1.         5.         1.16666667]]
sample 3:
Matrix 1: [[2 5 1]
 [3 6 3]
 [6 1