<a href="https://colab.research.google.com/github/LaFFF2300/Citie/blob/main/Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Task 1
Create a function named mat_desc() that througouhly describes a matrix, it should:


1.   Displays the shape, size, and rank of the matrix.
2.   Displays whether the matrix is square or non-square.
3.   Displays whether the matrix is an empty matrix.
4.   Displays if the matrix is an identity, ones, or zeros matrix

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
import numpy as np

In [18]:
# mat_desc function

def mat_desc(matrix):
  square = False
  matrix = np.array(matrix)
  print(matrix)
  print('Shape', matrix.shape)
  print('Size', matrix.size)
  print('Rank', np.linalg.matrix_rank(matrix))
  if(matrix.shape[0] == matrix.shape[1]):
    square = True
    print('Square Matrix')
  else: 
    print('Non-Square Matrix')
  if(matrix.shape[0] == 0 and matrix.shape[1] == 0):
    print('Empty Matrix')
  else:
    print('Matrix in not empty')
  iden = np.identity(matrix.shape[0])
  if(square and (iden == matrix).all()):
    print('Identity Matrix')
  else:
    print('Not identity matrix')
  one = np.ones((matrix.shape[0], matrix.shape[1]))
  if(one == matrix).all ():
    print('Ones matrix')
  else:
    print('Not a Ones Matrix')
  zero = np.zeros((matrix.shape[0], matrix.shape[1]))
  if((zero == matrix).all()):
    print('Zero Matrix')
  else:
    print('Non-Zero Matrix')

In [ ]:
print ('Matrix 1:')
mat_desc([[12,14,22], [2,4,6], [18,21,23], [23,24,25]])

print ('Matrix 2:')
mat_desc([[31,34,37], [43,46,49], [19,22,25], [12,12,12]])

print ('Matrix 3:')
mat_desc([[7,14,21], [1,2,3], [3,4,5], [5,6,7]])

print ('Matrix 4:')
mat_desc([[8,9,10], [12,16,20], [13,14,19], [12,16,18]])

print ('Matrix 5:')
mat_desc([[12,23,23], [2,22,22], [14,21,21], [5,10,10]])

Matrix 1:
[[12 14 22]
 [ 2  4  6]
 [18 21 23]
 [23 24 25]]
Shape (4, 3)
Size 12
Rank 3
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix 2:
[[31 34 37]
 [43 46 49]
 [19 22 25]
 [12 12 12]]
Shape (4, 3)
Size 12
Rank 2
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix 3:
[[ 7 14 21]
 [ 1  2  3]
 [ 3  4  5]
 [ 5  6  7]]
Shape (4, 3)
Size 12
Rank 2
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix 4:
[[ 8  9 10]
 [12 16 20]
 [13 14 19]
 [12 16 18]]
Shape (4, 3)
Size 12
Rank 3
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix
Matrix 5:
[[12 23 23]
 [ 2 22 22]
 [14 21 21]
 [ 5 10 10]]
Shape (4, 3)
Size 12
Rank 2
Non-Square Matrix
Matrix in not empty
Not identity matrix
Not a Ones Matrix
Non-Zero Matrix


###Task 2


Create a function named mat_operations() that takes in two matrices a input parameters it should:



1.   Determines if the matrices are viable for operation and returns your own error message if they are not viable.
2.   Returns the sum of the matrices.
3.   Returns the differen of the matrices.
4.   Returns the element-wise multiplication of the matrices.
5.   Returns the element-wise division of the matrices.

Use 5 sample matrices in which their shapes are not lower than (3,3). In your methodology, create a flowchart discuss the functions and methods you have done. Present your results in the results section showing the description of each matrix you have declared.

In [ ]:
def mat_operations(M1, M2) :
    comp=True
    n=0
    for i in M1:
      if len(i) !=len(M2 [n]):
          comp=False
      n+=1
    output=[]
    if comp:
      n=0
      for i in M1:
        add=[]
        m=0
        for j in i:
          add.append(j+M2[n][m])
          m+=1
        n+=1
        output.append(add)
    return output

In [ ]:
def mat_operations(mat1,mat2,result):
  for i in range(size1):
    for j in range(size2):
      result[i][j]=mat1[i][j]-mat2[i][j]

In [ ]:
def mat_operation(A,B):
  result=[[1,2,3,4,5], [1,1,1,1,1], [2,2,2,2,2] ] 
  for i in range (len(A)):
    for j in range (len(B[0])):
      for k in range(len(B)):
        result[i][j] += A[i][k]

  for p in result: 
      print (p)
  return 0